spring:
  application:
    name: 68Ashokit
server:
  port: 8761
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#  server:
#    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
